# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "assignment1-basic-app"
client_id = "fbcb120784c941cbc1f4ccc035cbce65"
application_url = "https://encoding-reveal-grass-lafayette.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://encoding-reveal-grass-lafayette.trycloudflare.com/auth/callback",
  "https://encoding-reveal-grass-lafayette.trycloudflare.com/auth/shopify/callback",
  "https://encoding-reveal-grass-lafayette.trycloudflare.com/api/auth/callback",
  "https://encoding-reveal-grass-lafayette.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ostadstorebd.myshopify.com"
